### ISSUE TITLE
As a user in a game, I want to get information about my state, such that I know when my turn is.

### ISSUE THREAD

**Issue by ElenaGrafUZH** [sopra-fs22-group-29/brandi-client#65]
**Acceptance Criteria**

- If it's the players turn, the player sees an information "Your turn!"
- If the player needs to wait until it is the players turn again, the players sees an information "Waiting..."

**Tasks**
- [ ] Frontend: Box where information about game state is displayed
- [ ] Frontend: get player state and update it via websockets
- [ ] Backend: set and update player state in current game
